# Generated by Django 4.1 on 2022-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(auto_now=True)),
                ('order_name', models.CharField(max_length=150)),
                ('order_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
